### PR TITLE
v7

### PR DESCRIPTION
**Pull request by 117**
# 🦙 Alpaca Trading SDK v7 (work in progress)

> [!NOTE]\
> Although this is a breaking change, the deprecated v6 will remain accessible through NPM if you are unable to make the necessary modifications to your code at this time.

## Why v7?

I'm updating the Alpaca Trading SDK to include the latest endpoints for both crypto and stocks. To simplify future modifications, types have been consolidated alongside a reduction in the total number of files, lowering the overall code complexity.

## Example

```tsx
import { Client } from "@master-chief/alpaca-ts";

const client = new Client({
  paper: true,
  credentials: {
    key: "PK4Z802QBVAC6V4YMUV7",
    secret: "WEK6HzUjrtjTdVhvKhoQdp6DSn0ZujFOVhgUZkzZ",
  },
});

client.v2.getAccount().then((account) => {
  console.log(account);
});
```

## Contributing

I hope that these updates will improve your overall experience with the Alpaca Trading SDK. If you have any feedback or suggestions, please let me know! Feel free to PR v7 branch.

### CODE REVIEW

**Comment by 117** [comment]
@iukea1 the endpoints are done i just need to do all the typings

**Comment by iukea1** [comment]
> @iukea1 the endpoints are done i just need to do all the typings

You are  the man!

I am working on a NextJS project and I am excited to use the typescript equivalent of the Alpaca API

**Comment by iukea1** [comment]
> @iukea1 the endpoints are done i just need to do all the typings

By any chance did you get to work on this? I am just trying to figure out if I should use the other alpaca library for js.

Just I am trying to be a good boy and only use typescript (I am a noob when it comes to JS and typescript)

**Comment by 117** [comment]
@iukea1 I wish I had the time, I keep trying but the days slip by. :/ If you use v6 for now it's a small lift to switch over to v7. All of the types will have the same fields.

**Comment by DaviDevMod** [comment]
@117  Love what you are doing here.

Is there any chance to get the current state of v7 as a pre-alpha release so that I can paper trade cryptos while waiting for the work to progress?

**Comment by 117** [comment]
@DaviDevMod Hey! So no guarantee on typings being entirely accurate, however the REST endpoints should mostly all done. I setup an example here, the latest version is `7.0.2-alpha`.

https://codesandbox.io/p/sandbox/xenodochial-framework-kf3ktz

I will work on streaming next. Please complain about any and everything you find. The more the better 😄

**Comment by 117** [comment]
image

**Comment by DaviDevMod** [comment]
@117 Wow that was quick! Thank you so much.

I'll try to complain as much as possible :laughing:

It looks like my setup can't find type declarations for v7.0.2-alpha, I'll let you know what's the problem.
For the moment I will only complain about a missing `dist` in the `.gitignore`.

Thank you again for the release! :tada:

**Comment by 117** [comment]
> @117 Wow that was quick! Thank you so much.
> 
> I'll try to complain as much as possible 😆
> 
> It looks like my setup can't find type declarations for v7.0.2-alpha, I'll let you know what's the problem. For the moment I will only complain about a missing `dist` in the `.gitignore`.
> 
> Thank you again for the release! 🎉

odd they should be in   "types": "./@types/index.d.ts",

**Comment by iukea1** [comment]
sweeeeeeeeeeeeeeettt

**Comment by DaviDevMod** [comment]
> generating the typings from openapi spec

Please forgive my ignorance, I never worked with openapi.
Do you mean that having the typings in a "@typing" folder is an openapi standard?

https://github.com/alpacahq/alpaca-ts/blob/17410b983ea75566159b18d43ae5d72b00f806f7/tsconfig.json#L19

My setup can find the type declarations if they are generated alongside the .js files, but surely there must be a way to make that `"declarationDir"` work.
I'll look into it when possible.
By the way can you reproduce the issue or importing `"@master-chief/alpaca-ts"` with the v7.0.2-alpha just works for you?

**Comment by 117** [comment]
> > generating the typings from openapi spec
> 
> Please forgive my ignorance, I never worked with openapi. Do you mean that having the typings in a "@typing" folder is an openapi standard?
> 
> https://github.com/alpacahq/alpaca-ts/blob/17410b983ea75566159b18d43ae5d72b00f806f7/tsconfig.json#L19
> 
> My setup can find the type declarations if they are generated alongside the .js files, but surely there must be a way to make that `"declarationDir"` work. I'll look into it when possible. By the way can you reproduce the issue or importing `"@master-chief/alpaca-ts"` with the v7.0.2-alpha just works for you?

ill tag you in next release

image

im using generated classes and a custom client to interface with them. should all work out of the box

**Comment by 117** [comment]
types are [done](https://github.com/alpacahq/alpaca-ts/tree/v7/src/models). and good news. both stock and crypto market data endpoints will be included. i will finish the rest client probably tomorrow so its not quite usable yet. i think i should release it without a websocket client at first, it is an alpha anyways

**Comment by 117** [comment]
we're almost there 😬

**Comment by DaviDevMod** [comment]
@117 Really appreciate all the work you are putting in. Hope you manage to release without too many troubles :rocket:

I'm sure eventually you would notice that too, but there are a bunch of duplicate `symbol` identifiers in `src/services/StockPricingDataApiService.ts`. 

https://github.com/alpacahq/alpaca-ts/blob/8a6dd61d35d0dc81fc41c4e5c4cd27f985fa3bfd/src/services/StockPricingDataApiService.ts#L316

You can get a list of them by trying to build the library :laughing:

**Comment by 117** [comment]
I've refactored the client. There may be some issues I don't know about yet, but let me know if this version works for you 😁! Most if not all the REST endpoints are there. There is no built in rate-limiting, ill add that next.

```console
npm i @master-chief/alpaca-ts@7.0.5-alpha
```

```ts
import { Client } from "@master-chief/alpaca-ts";

const client = new Client({
  paper: true, // not necessary but just to show it's there by default
  credentials: {
    key: "PK4Z802QBVAC6V4YMUV7",
    secret: "WEK6HzUjrtjTdVhvKhoQdp6DSn0ZujFOVhgUZkzZ",
  },
});

client.account.getAccount().then((account) => {
  console.log(account);
});
```

**Comment by DaviDevMod** [comment]
@117 Looks great! :tada: The typings work and I am able to log my account.

However if I try to get crypto bars, I get `'endpoint not found.'`
It may be that there's something wrong in my request though.
Here's my code:

```ts
const bars = await client.crypto.getBarsForCryptoSymbol({
  symbol: "ETH/BTC",
  start: "2023-07-22 00:00:00",
  end: "2023-07-23 00:00:00",
  timeframe: "1Hour",
});

console.log(bars);
```
And the error:
```
{
  url: 'https://paper-api.alpaca.markets/v1beta1/crypto/ETH/BTC/bars?start=2023-07-22%2000%3A00%3A00&end=2023-07-23%2000%3A00%3A00&timeframe=1Hour',
  status: 404,
  statusText: 'Not Found',
  body: { message: 'endpoint not found.' },
  request: {
    method: 'GET',
    url: '/v1beta1/crypto/{symbol}/bars',
    path: { symbol: 'ETH/BTC' },
    query: {
      start: '2023-07-22 00:00:00',
      end: '2023-07-23 00:00:00',
      timeframe: '1Hour',
      exchanges: undefined,
      limit: undefined,
      page_token: undefined
    }
  }
}
```

Note that I tried various date formats, like using a "T" `"2023-07-22T00:00:00"`, or adding fractions of a second `"2023-07-22 00:00:00+00:00:00"` (though they are [not supported](https://github.com/alpacahq/alpaca-ts/blob/fb689f45e02cc5af49ee48e00d154e8621ebbbc7/src/services/CryptoDataService.ts#L318)), or omitting the dates altogether since they are optional parameters.

Any idea on why the endpoint is not found?

**Comment by 117** [comment]
> @117 Looks great! 🎉 The typings work and I am able to log my account.
> 
> However if I try to get crypto bars, I get `'endpoint not found.'` It may be that there's something wrong in my request though. Here's my code:
> 
> ```ts
> await client.crypto.getBarsForCryptoSymbol({
>   symbol: "ETH/BTC",
>   start: "2023-07-22 00:00:00",
>   end: "2023-07-23 00:00:00",
>   timeframe: "1Hour",
> });
> ```
> 
> And the error:
> 
> ```
> {
>   url: 'https://paper-api.alpaca.markets/v1beta1/crypto/ETH/BTC/bars?start=2023-07-22%2000%3A00%3A00&end=2023-07-23%2000%3A00%3A00&timeframe=1Hour',
>   status: 404,
>   statusText: 'Not Found',
>   body: { message: 'endpoint not found.' },
>   request: {
>     method: 'GET',
>     url: '/v1beta1/crypto/{symbol}/bars',
>     path: { symbol: 'ETH/BTC' },
>     query: {
>       start: '2023-07-22 00:00:00',
>       end: '2023-07-23 00:00:00',
>       timeframe: '1Hour',
>       exchanges: undefined,
>       limit: undefined,
>       page_token: undefined
>     }
>   }
> }
> ```
> 
> Note that I tried various date formats, like using a "T" `"2023-07-22T00:00:00"`, or adding fractions of a second `"2023-07-22 00:00:00+00:00:00"` (though they are [not supported](https://github.com/alpacahq/alpaca-ts/blob/fb689f45e02cc5af49ee48e00d154e8621ebbbc7/src/services/CryptoDataService.ts#L316)), or omitting `start` and `end` altogether since they are optional parameters.
> 
> Any idea on why the endpoint is not found?

Ah. It needs to be using `data.alpaca.markets`

**Comment by 117** [comment]
> @117 Looks great! 🎉 The typings work and I am able to log my account.
> 
> However if I try to get crypto bars, I get `'endpoint not found.'` It may be that there's something wrong in my request though. Here's my code:
> 
> ```ts
> await client.crypto.getBarsForCryptoSymbol({
>   symbol: "ETH/BTC",
>   start: "2023-07-22 00:00:00",
>   end: "2023-07-23 00:00:00",
>   timeframe: "1Hour",
> });
> ```
> 
> And the error:
> 
> ```
> {
>   url: 'https://paper-api.alpaca.markets/v1beta1/crypto/ETH/BTC/bars?start=2023-07-22%2000%3A00%3A00&end=2023-07-23%2000%3A00%3A00&timeframe=1Hour',
>   status: 404,
>   statusText: 'Not Found',
>   body: { message: 'endpoint not found.' },
>   request: {
>     method: 'GET',
>     url: '/v1beta1/crypto/{symbol}/bars',
>     path: { symbol: 'ETH/BTC' },
>     query: {
>       start: '2023-07-22 00:00:00',
>       end: '2023-07-23 00:00:00',
>       timeframe: '1Hour',
>       exchanges: undefined,
>       limit: undefined,
>       page_token: undefined
>     }
>   }
> }
> ```
> 
> Note that I tried various date formats, like using a "T" `"2023-07-22T00:00:00"`, or adding fractions of a second `"2023-07-22 00:00:00+00:00:00"` (though they are [not supported](https://github.com/alpacahq/alpaca-ts/blob/fb689f45e02cc5af49ee48e00d154e8621ebbbc7/src/services/CryptoDataService.ts#L316)), or omitting `start` and `end` altogether since they are optional parameters.
> 
> Any idea on why the endpoint is not found?

Okay. Ive fixed the path for that endpoint in particular, try this on latest build:

```tsx
client.crypto
  .getBarsForCryptoSymbol({
    symbols: "ETH/USD",
    start: "2023-07-22",
    end: "2023-07-23",
    timeframe: "1Min",
  })
  .then((data) => {
    console.log(data);
  });
```

The OpenAPI spec did not include v1beta3, v1beta2 was deprecated.

**Comment by 117** [comment]
I'll fix all the other crypto endpoints.. 😢

**Comment by 117** [comment]
They should be fixed.. let me know if you run into an issue.

**Comment by DaviDevMod** [comment]
@117 Now the crypto endpoint works :partying_face: but I can't get my account anymore :grimacing:

I think that v7.0.6-alpha was the last one in which the account worked properly.

I put together a basic setup you can use to test your work the same way I do.

It's in the `basic-setup` branch of this repo: https://github.com/DaviDevMod/dabot

You can try stuff in `index.ts`.
There's a `"compile-n-run"` script to run the file.
There's also an `"update-local-alpaca"` script installing a local build of alpaca-ts (you'll probably need to tweak the path to your local tarball tough).

To use the local build, just `npm run build && npm pack` alpaca-ts, then in the basic setup `npm run update-local-alpaca`.

Obviously, you can always install a version from npmjs instead.

Hope it's going to help.

**Comment by 117** [comment]
Yeah i messed up, quickly fixing the data path before. I overwrote the account path.

**Comment by 117** [comment]
@DaviDevMod thanks for the repo. ill figure out a more robust solution for the multiple base urls needed

**Comment by 117** [comment]
doing quite a bit of a refactor. might as well have written it from scratch lol. will tag you when i have it ready for testing. might be a few days

**Comment by bennycode** [comment]
I just tried @master-chief/alpaca-ts v7.0.9-alpha with the example code provided:

```ts
import {Client} from '@master-chief/alpaca-ts';

const client = new Client({
  paper: true,
  credentials: {
    key: 'top-secret',
    secret: 'top-secret',
  },
});

client.account.getAccount().then((account) => {
  console.log(account);
});
``` 

When running the example it returns the following error:

> ApiError: Not Found

```json
{
  "body": {
    "message": "endpoint not found."
  },
  "request": {
    "method": "GET",
    "url": "/v2/account"
  },
  "status": 404,
  "statusText": "Not Found",
  "url": "https://data.alpaca.markets/v2/account"
}
```

From what I understood, the base URL must be https://paper-api.alpaca.markets instead of https://data.alpaca.markets/ when `paper` is set to `true`, no?

**Comment by 117** [comment]
back to this now. ill tag you when ready

**Comment by 117** [comment]
Okay guys! Please try `7.0.10-alpha`. You can try it on CodeSandbox [here](https://codesandbox.io/p/sandbox/confident-dhawan-4ylsql?file=%2Fpackage.json%3A24%2C19).

```tsx
import { Client } from "@master-chief/alpaca-ts";

const client = new Client({
  paper: true,
  credentials: {
    key: "PK4Z802QBVAC6V4YMUV7",
    secret: "WEK6HzUjrtjTdVhvKhoQdp6DSn0ZujFOVhgUZkzZ",
  },
});

client.v2.getAccount().then((account) => {
  console.log(account);
});

// {
//   id: '840930b7-0771-43f0-9eb4-2b3db2fa7f24',
//     admin_configurations: {},
//   user_configurations: null,
//     account_number: 'PA3QAUAUE952',
//   status: 'ACTIVE',
//   crypto_status: 'ACTIVE',
//   currency: 'USD',
//   buying_power: '10293.205',
//   regt_buying_power: '10293.205',
//   daytrading_buying_power: '0',
//   effective_buying_power: '10293.205',
//   non_marginable_buying_power: '4921.57',
//   bod_dtbp: '0',
//   cash: '4921.57',
//   accrued_fees: '0',
//   pending_transfer_in: '0',
//   portfolio_value: '5371.635',
//   pattern_day_trader: false,
//   trading_blocked: false,
//   transfers_blocked: false,
//   account_blocked: false,
//   created_at: '2023-06-01T17:34:01.721563Z',
//   trade_suspended_by_user: false,
//   multiplier: '2',
//   shorting_enabled: true,
//   equity: '5371.635',
//   last_equity: '5368.38',
//   long_market_value: '450.065',
//   short_market_value: '0',
//   position_market_value: '450.065',
//   initial_margin: '225.0325',
//   maintenance_margin: '135.0195',
//   last_maintenance_margin: '134.04',
//   sma: '5370.41',
//   daytrade_count: 0,
//   balance_asof: '2023-08-04',
//   crypto_tier: 1
// }

```

**Comment by bennycode** [comment]
Hey @117, thanks for your fast reply! Much appreciated. 😊

I just had a test using `await this.client.v2.getClock()` & `await this.client.v2.getAllOpenPositions()` with "@master-chief/alpaca-ts" v7.0.10-alpha and it worked. 🥳🥳🥳

**Comment by 117** [comment]
Next up.. is websocket and revised README doc.

**Comment by bennycode** [comment]
Thank you for your support @117!

I was testing `client.v1beta3.getBars` today and noticed another 404 error:

```json
{
  "status": 404,
  "statusText": "Not Found",
  "url": "https://api.alpaca.markets/v1beta3/crypto/us/bars?symbols=..."
}
``` 

When testing on https://docs.alpaca.markets/reference/v1beta3cryptobars I noitced that it queries https://data.alpaca.markets/v1beta3/crypto/us/bars and not https://api.alpaca.markets/v1beta3/crypto/us/bars - Is this another base URL confusion?

**Comment by 117** [comment]
> Thank you for your support @117!
> 
> I was testing `client.v1beta3.getBars` today and noticed another 404 error:
> 
> ```json
> {
>   "status": 404,
>   "statusText": "Not Found",
>   "url": "https://api.alpaca.markets/v1beta3/crypto/us/bars?symbols=..."
> }
> ```
> 
> When testing on https://docs.alpaca.markets/reference/v1beta3cryptobars I noitced that it queries https://data.alpaca.markets/v1beta3/crypto/us/bars and not https://api.alpaca.markets/v1beta3/crypto/us/bars - Is this another base URL confusion?

yep ill update it

**Comment by 117** [comment]
@bennycode try now on `7.0.11-alpha`

```tsx
import { Client } from "@master-chief/alpaca-ts";

const client = new Client({
  paper: true,
  credentials: {
    key: "PK4Z802QBVAC6V4YMUV7",
    secret: "WEK6HzUjrtjTdVhvKhoQdp6DSn0ZujFOVhgUZkzZ",
  },
});

client.v1beta3
  .getCryptoBars({ symbols: "BTC/USD", timeframe: "1Min" })
  .then(({ bars }) => {
    console.log(bars);
  });

// {
//   'BTC/USD': [
//   {
//     c: 29270.5062,
//     h: 29270.5062,
//     l: 29270.5062,
//     n: 1,
//     o: 29270.5062,
//     t: '2023-08-08T05:44:00Z',
//     v: 0.000339933,
//     vw: 29270.5062
//   },
//   {
//     c: 29125.4,
//     h: 29125.4,
//     l: 29125.4,
//     n: 1,
//     o: 29125.4,
//     t: '2023-08-08T07:48:00Z',
//     v: 0.000071048,
//     vw: 29125.4
//   },
//   ...
```

**Comment by bennycode** [comment]
**Thanks for the update.** I upgraded the package (to v7.0.11-alpha) and changed `client.v1beta3.getBars` to `client.v1beta3.getCryptoBars`. Now it works! 😊

**Comment by 117** [comment]
> **Thanks for the update.** I upgraded the package (to v7.0.11-alpha) and changed `client.v1beta3.getBars` to `client.v1beta3.getCryptoBars`. Now it works! 😊

still doing a lot of refactoring. those crypto method names will stay the same. but others are changing to be more consistent. order placement method also looks broken

**Comment by bennycode** [comment]
> still doing a lot of refactoring. those crypto method names will stay the same. but others are changing to be more consistent. order placement method also looks broken

I am more than happy to support you with testing. 😊 Where can I actually get the bars for non-crypto assets? Your docs say [/v2/stocks/bars](https://docs.alpaca.markets/reference/stockbars) but I am not seeing this being exposed on `client.v2`. 🤔

**Comment by 117** [comment]
@bennycode oops. added in `7.0.12-alpha`. for all of these calls they will be nested in the version in the docs

```tsx
client.v2
  .getStocksBars({ symbols: "SPY", timeframe: "1Min" })
  .then(({ bars }) => {
    console.log(bars);
  });

// {
//   SPY: [
//     {
//       t: '2023-08-08T08:00:00Z',
//       o: 449.85,
//       h: 449.96,
//       l: 449.82,
//       c: 449.83,
//       v: 4226,
//       n: 30,
//       vw: 449.834134
//     },
//     ...
```

**Comment by bennycode** [comment]
Great, one step further! 💪 

I noticed that `client.v2.getAllOpenPositions()` is broken with `7.0.12-alpha`:

```json
{
  "body": {
    "message": "endpoint not found."
  },
  "request": {
    "method": "GET",
    "url": "/v2/positions"
  },
  "status": 404,
  "statusText": "Not Found",
  "url": "https://data.alpaca.markets/v2/positions"
}
```
I guess the base URL here has to be `api.alpaca.markets` (or `paper-api.alpaca.markets`) instead of `data.alpaca.markets`? Is there a trick (quickfix), how I can change the base URL myself in case I discover more of these hiccups?

**Comment by 117** [comment]
@bennycode what was happening is the `BASE` was being set on the persistent `baseHttpRequest`. so if you went from calling a data endpoint to a non-data endpoint, the base url was not changing.

fixed that with a temporary hack, ill revisit a more robust solution for handling the multiple possible base urls. the following is working for me:

`7.0.13-alpha`

```tsx
client.v2
  .getStocksBars({ symbols: "SPY", timeframe: "1Min" })
  .then(({ bars }) => {
    console.log(bars);
  });

client.v2.getPositions().then((positions) => {
  console.log(positions);
});

```

**Comment by bennycode** [comment]
I changed from `client.v2.getAllOpenPositions` to `client.v2.getPositions` with `7.0.13-alpha` and it works. 👍

**Comment by 117** [comment]
Im juggling work and this, ill keep doing a bit each day until its ready. Glad that works for now :)Sent from my iPhoneOn Aug 8, 2023, at 5:03 PM, Benny Neugebauer ***@***.***> wrote:﻿
I changed from client.v2.getAllOpenPositions to client.v2.getPositions with 7.0.13-alpha and it works. 👍

**Comment by bennycode** [comment]
I appreciate your help very much! 👍 I am the creator of a [Coinbase API for Node.js](https://github.com/bennycode/coinbase-pro-node) and know how much work it is to maintain a stable and current SDK.

I just tested `client.v1beta3.getCryptoBarsLatest` and noticed that it wants me to provide an exchange (`"ERSX" | "CBSE" | "FTXU"`). Unfortunately, the `exchange` param is not defined here: https://docs.alpaca.markets/reference/cryptolatestbars - Is it something new?

**Comment by 117** [comment]
Back to this today. Will fix that.

**Comment by 117** [comment]
I refactored methods like `getStocksBars` to `getStockBars`. Similar to `getCrypto` you can infer `getStock` to be plural or singular. So you may need to change those methods if you are using them right now.

**Comment by 117** [comment]
latest published `7.0.14-alpha`

**Comment by bennycode** [comment]
Just tested `client.v2.getStockBarsLatest` & `client.v1beta3.getCryptoBarsLatest`. They are working well. Thanks. 👍

**Comment by bennycode** [comment]
Today I have been using `client.v2.getAssets` which returns an `Asset`. I noticed that `Asset` is not fully typed. When you retrieve a crypto asset, then it has properties like `min_order_size` or `min_trade_increment`. These props are not part of `Asset`. 

It would be great if there was a union type for `Asset` and `CryptoAsset`, so that I could narrow down the properties with a descriminator like `class`:

```ts
if (asset.class === 'crypto') {
  console.log(asset.min_order_size);
}
```

**Comment by bennycode** [comment]
How can `client.v2.postOrder` be used? It only supports a `requestBody` of type `string`:

image

**Comment by 117** [comment]
busy ):

**Comment by UchihaVeha** [comment]
Hi, is it abandoned? I need to remove raw functions from entities for memory optimization. Can I upgrade to this version from v6, or is it unfinished for production?

**Comment by aqilc** [comment]
Damn you actually became active for once? If you need help I can take over.

**Comment by bennycode** [comment]
I'm using a combination of SDK v6 and SDK v7 to overcome any limitations. This method involves including both references in the `dependencies` list of the `package.json` file:

```json
"dependencies": {
  "@master-chief/alpaca-ts": "^7.0.15-alpha",
  "alpaca-legacy": "npm:@master-chief/alpaca@^6.3.20"
}
```

Afterwards, both SDKs can be used in parallel like this:

```ts
import { Client } from "@master-chief/alpaca-ts";
import {
  AlpacaClient as LegacyClient
  // @ts-ignore:next-line
} from "alpaca-legacy";

const client = new Client(...);
const legacyClient = new LegacyClient(...);
```

**Comment by 117** [comment]
@bennycode do you like the approach/pattern of v7?

**Comment by bennycode** [comment]
> @bennycode do you like the approach/pattern of v7?

Yes, I am very happy with v7! My application is quite sophisticated. If you'd like, I can provide feedback to one of your product managers.

I am using the legacy client only for placing orders and for connecting to `AlpacaStream`.

**Comment by 117** [comment]
@bennycode i have a new repo for this underway, spent the last 8 hours going through the docs line by line lol. this one is handwritten not codegen using api spec. will post here after i clean it up

**Comment by 117** [comment]
@bennycode https://github.com/alpacahq/typescript-sdk almost done. v7 can be considered abandoned. The new repo is comprehensive, covers all endpoints (minus broker api), and all streams.

**Pull request closed without merging**
